-- =========================================================
-- V1__init_schema.sql
-- GLIT 커리어 기록 서비스 초기 스키마
--
-- 정책:
--  - Enum: PostgreSQL native enum 대신 VARCHAR + CHECK 제약 (Hibernate @Enumerated STRING 호환)
--  - Timestamp: 전부 TIMESTAMPTZ (UTC 저장, 엔티티 OffsetDateTime과 매핑)
--  - BaseTimeEntity / SoftDeleteEntity @MappedSuperclass → 각 테이블에 인라인 컬럼으로 펼침
--  - append-only 테이블(user_term_agreements) UPDATE/DELETE 금지는 애플리케이션 레벨 규약
--  - 시간 의존 CHECK(scrums.scrum_date 범위 등)은 PG IMMUTABLE 제약으로 표현 불가 → 애플리케이션 레벨 검증
-- =========================================================


-- =========================================================
-- USER
-- =========================================================
CREATE TABLE users (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname       VARCHAR(12)  NOT NULL,
    job_role       VARCHAR(20)  NOT NULL,
    user_status    VARCHAR(20)  NOT NULL,
    branding_title VARCHAR(100),
    last_login_at  TIMESTAMPTZ,
    hard_delete_at TIMESTAMPTZ,
    is_deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_users_job_role    CHECK (job_role    IN ('PLANNER', 'DEVELOPER', 'DESIGNER')),
    CONSTRAINT ck_users_user_status CHECK (user_status IN ('STUDENT', 'JOB_SEEKER', 'EMPLOYED'))
);
CREATE INDEX idx_users_nickname          ON users (nickname);
CREATE INDEX idx_users_active_last_login ON users (is_deleted, last_login_at);


-- =========================================================
-- AUTH
-- =========================================================
CREATE TABLE social_accounts (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    provider     VARCHAR(20)  NOT NULL,
    provider_uid VARCHAR(255) NOT NULL,
    email        VARCHAR(255),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_social_accounts_user     FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_social_accounts_provider CHECK (provider IN ('KAKAO', 'GOOGLE', 'NAVER'))
);
CREATE UNIQUE INDEX uq_social_accounts_provider_uid  ON social_accounts (provider, provider_uid);
CREATE UNIQUE INDEX uq_social_accounts_user_provider ON social_accounts (user_id, provider);


CREATE TABLE auth_tokens (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT       NOT NULL,
    refresh_token_hash VARCHAR(255) NOT NULL,
    device_id          VARCHAR(100),
    expires_at         TIMESTAMPTZ  NOT NULL,
    revoked_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_auth_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE UNIQUE INDEX uq_auth_tokens_refresh_token_hash ON auth_tokens (refresh_token_hash);
CREATE INDEX        idx_auth_tokens_user_revoked_at  ON auth_tokens (user_id, revoked_at);
CREATE INDEX        idx_auth_tokens_expires_at       ON auth_tokens (expires_at);


CREATE TABLE device_tokens (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    platform   VARCHAR(20)  NOT NULL,
    push_token VARCHAR(255) NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_device_tokens_user     FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_device_tokens_platform CHECK (platform IN ('IOS', 'ANDROID', 'WEB'))
);
CREATE UNIQUE INDEX uq_device_tokens_push_token    ON device_tokens (push_token);
CREATE INDEX        idx_device_tokens_user_active ON device_tokens (user_id, is_active);


-- =========================================================
-- RECORD: Project / ScrumTitle / Scrum
-- =========================================================
CREATE TABLE projects (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    name        VARCHAR(15) NOT NULL,
    title_count SMALLINT    NOT NULL DEFAULT 0,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX        idx_projects_user_is_deleted       ON projects (user_id, is_deleted);
CREATE UNIQUE INDEX uq_projects_user_name_is_deleted   ON projects (user_id, name, is_deleted);


CREATE TABLE scrum_titles (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    project_id  BIGINT      NOT NULL,
    free_text   VARCHAR(20) NOT NULL,
    scrum_count SMALLINT    NOT NULL DEFAULT 0,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_scrum_titles_user    FOREIGN KEY (user_id)    REFERENCES users(id),
    CONSTRAINT fk_scrum_titles_project FOREIGN KEY (project_id) REFERENCES projects(id)
);
CREATE INDEX idx_scrum_titles_user_is_deleted    ON scrum_titles (user_id, is_deleted);
CREATE INDEX idx_scrum_titles_project_is_deleted ON scrum_titles (project_id, is_deleted);


CREATE TABLE scrums (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT      NOT NULL,
    title_id            BIGINT      NOT NULL,
    content             VARCHAR(50) NOT NULL,
    scrum_date          DATE        NOT NULL,
    has_star            BOOLEAN     NOT NULL DEFAULT FALSE,
    selected_competency VARCHAR(30),
    is_deleted          BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_scrums_user                FOREIGN KEY (user_id)  REFERENCES users(id),
    CONSTRAINT fk_scrums_title               FOREIGN KEY (title_id) REFERENCES scrum_titles(id),
    CONSTRAINT ck_scrums_selected_competency CHECK (
        selected_competency IS NULL OR selected_competency IN (
            'DISCOVERY_ANALYSIS', 'PLANNING_EXECUTION', 'COLLABORATION', 'PROBLEM_SOLVING', 'REFLECTION_GROWTH'
        )
    )
    -- NOTE: scrum_date 범위(당일 기준 최근 14일 이내, 미래 불가) CHECK은 CURRENT_DATE가 STABLE이라 불가 → 앱 레벨 검증
);
CREATE INDEX idx_scrums_user_scrum_date            ON scrums (user_id, scrum_date);
CREATE INDEX idx_scrums_title_is_deleted           ON scrums (title_id, is_deleted);
CREATE INDEX idx_scrums_user_scrum_date_is_deleted ON scrums (user_id, scrum_date, is_deleted);
CREATE INDEX idx_scrums_user_created_at            ON scrums (user_id, created_at);


-- =========================================================
-- STAR
-- =========================================================
CREATE TABLE star_records (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL,
    scrum_id       BIGINT      NOT NULL,
    situation_task TEXT,
    action         TEXT,
    result         TEXT,
    current_step   VARCHAR(10) NOT NULL DEFAULT 'ST',
    is_completed   BOOLEAN     NOT NULL DEFAULT FALSE,
    completed_at   TIMESTAMPTZ,
    is_deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_star_records_user         FOREIGN KEY (user_id)  REFERENCES users(id),
    CONSTRAINT fk_star_records_scrum        FOREIGN KEY (scrum_id) REFERENCES scrums(id),
    CONSTRAINT ck_star_records_current_step CHECK (current_step IN ('ST', 'A', 'R', 'DONE'))
);
CREATE UNIQUE INDEX uq_star_records_scrum_id            ON star_records (scrum_id);
CREATE INDEX        idx_star_records_user_completed_at ON star_records (user_id, completed_at);
CREATE INDEX        idx_star_records_user_is_completed ON star_records (user_id, is_completed);


CREATE TABLE star_images (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    star_record_id BIGINT       NOT NULL,
    image_url      VARCHAR(500) NOT NULL,
    mime_type      VARCHAR(20)  NOT NULL,
    size_bytes     INTEGER      NOT NULL,
    sort_order     SMALLINT     NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_star_images_star_record FOREIGN KEY (star_record_id) REFERENCES star_records(id)
);
CREATE UNIQUE INDEX uq_star_images_star_record_sort_order ON star_images (star_record_id, sort_order);


CREATE TABLE star_tags (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    star_record_id   BIGINT      NOT NULL,
    primary_category VARCHAR(30) NOT NULL,
    detail_tag       VARCHAR(50) NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_star_tags_star_record      FOREIGN KEY (star_record_id) REFERENCES star_records(id),
    CONSTRAINT ck_star_tags_primary_category CHECK (primary_category IN (
        'DISCOVERY_ANALYSIS', 'PLANNING_EXECUTION', 'COLLABORATION', 'PROBLEM_SOLVING', 'REFLECTION_GROWTH'
    ))
);
CREATE UNIQUE INDEX uq_star_tags_star_record_detail_tag ON star_tags (star_record_id, detail_tag);
CREATE INDEX        idx_star_tags_primary_category     ON star_tags (primary_category);


CREATE TABLE ai_tagging_jobs (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    star_record_id   BIGINT      NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    retry_count      SMALLINT    NOT NULL DEFAULT 0,
    request_payload  JSONB,
    response_payload JSONB,
    error_message    TEXT,
    started_at       TIMESTAMPTZ,
    finished_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_ai_tagging_jobs_star_record FOREIGN KEY (star_record_id) REFERENCES star_records(id),
    CONSTRAINT ck_ai_tagging_jobs_status      CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED'))
);
CREATE INDEX idx_ai_tagging_jobs_status_created_at ON ai_tagging_jobs (status, created_at);
CREATE INDEX idx_ai_tagging_jobs_star_record       ON ai_tagging_jobs (star_record_id);


-- =========================================================
-- DAILY COMPETENCY STATS
-- =========================================================
CREATE TABLE daily_competency_stats (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL,
    stat_date        DATE        NOT NULL,
    scrum_count      SMALLINT    NOT NULL DEFAULT 0,
    star_count       SMALLINT    NOT NULL DEFAULT 0,
    primary_category VARCHAR(30),
    category_counts  JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_daily_competency_stats_user             FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_daily_competency_stats_primary_category CHECK (
        primary_category IS NULL OR primary_category IN (
            'DISCOVERY_ANALYSIS', 'PLANNING_EXECUTION', 'COLLABORATION', 'PROBLEM_SOLVING', 'REFLECTION_GROWTH'
        )
    )
);
CREATE UNIQUE INDEX uq_daily_competency_stats_user_stat_date ON daily_competency_stats (user_id, stat_date);


-- =========================================================
-- REPORTS
-- =========================================================
CREATE TABLE reports (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    report_type   VARCHAR(20)  NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'GENERATING',
    star_count_at INTEGER      NOT NULL,
    title         VARCHAR(200),
    content_json  JSONB,
    retry_count   SMALLINT     NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_reports_user        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_reports_report_type CHECK (report_type IN ('MINI', 'CAREER')),
    CONSTRAINT ck_reports_status      CHECK (status      IN ('GENERATING', 'SUCCESS', 'FAILED'))
);
CREATE INDEX idx_reports_user_created_at             ON reports (user_id, created_at);
CREATE INDEX idx_reports_user_report_type_created_at ON reports (user_id, report_type, created_at);
CREATE INDEX idx_reports_status                      ON reports (status);


-- =========================================================
-- NOTIFICATION
-- =========================================================
CREATE TABLE notification_settings (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,
    notify_time TIME        NOT NULL,
    is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_notification_settings_user        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_notification_settings_day_of_week CHECK (
        day_of_week IN ('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN')
    ),
    -- notify_time 허용 슬롯: 00:00 (자정) 또는 07:00~23:30 중 30분 단위
    CONSTRAINT ck_notification_settings_notify_time CHECK (
        (notify_time >= TIME '07:00' OR notify_time = TIME '00:00')
        AND EXTRACT(MINUTE FROM notify_time) IN (0, 30)
        AND EXTRACT(SECOND FROM notify_time) = 0
    )
);
CREATE UNIQUE INDEX uq_notification_settings_user_day_time ON notification_settings (user_id, day_of_week, notify_time);
CREATE INDEX        idx_notification_settings_day_time_active ON notification_settings (day_of_week, notify_time, is_active);


-- =========================================================
-- TERMS
-- =========================================================
CREATE TABLE term_versions (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(30)  NOT NULL,
    version      VARCHAR(20)  NOT NULL,
    title        VARCHAR(200) NOT NULL,
    content_url  VARCHAR(500) NOT NULL,
    effective_at TIMESTAMPTZ  NOT NULL,
    is_required  BOOLEAN      NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_term_versions_type CHECK (type IN (
        'PRIVACY_POLICY', 'TERMS_OF_SERVICE', 'MARKETING', 'AGE_OVER_14'
    ))
);
CREATE UNIQUE INDEX uq_term_versions_type_version    ON term_versions (type, version);
CREATE INDEX        idx_term_versions_type_effective ON term_versions (type, effective_at);


-- append-only (앱 레벨에서 UPDATE/DELETE 금지 규약)
CREATE TABLE user_term_agreements (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    term_version_id BIGINT       NOT NULL,
    agreed          BOOLEAN      NOT NULL,
    agreed_at       TIMESTAMPTZ  NOT NULL,
    ip_address      VARCHAR(45),
    user_agent      VARCHAR(500),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_term_agreements_user         FOREIGN KEY (user_id)         REFERENCES users(id),
    CONSTRAINT fk_user_term_agreements_term_version FOREIGN KEY (term_version_id) REFERENCES term_versions(id)
);
CREATE INDEX idx_user_term_agreements_user_term_created
    ON user_term_agreements (user_id, term_version_id, created_at);
CREATE INDEX idx_user_term_agreements_user_agreed_at
    ON user_term_agreements (user_id, agreed_at);
CREATE INDEX idx_user_term_agreements_term_version
    ON user_term_agreements (term_version_id);


-- =========================================================
-- COACHMARK
-- =========================================================
CREATE TABLE coachmark_histories (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL,
    coachmark_key VARCHAR(50) NOT NULL,
    shown_at      TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_coachmark_histories_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE UNIQUE INDEX uq_coachmark_histories_user_coachmark_key ON coachmark_histories (user_id, coachmark_key);
